"""Added permissions table model

Revision ID: 2dbf5fb81463
Revises: c80e39ca6c81
Create Date: 2024-11-08 17:31:37.580911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf5fb81463'
down_revision = 'c80e39ca6c81'
branch_labels = None
depends_on = None

def upgrade():
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
