"""Added a new table named userdepartment to have relationship between users and departments

Revision ID: 5af796c955d2
Revises: 89bf21194c51
Create Date: 2024-11-21 10:43:37.654515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5af796c955d2'
down_revision = '89bf21194c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_department',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'dept_id')
    )
    op.drop_table('userdepartment')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_department_cascade', type_='foreignkey')

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_folder_cascade', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_folder_cascade', 'folders', ['folder_id'], ['folder_id'], ondelete='CASCADE')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_department_cascade', 'departments', ['dept_id'], ['dept_id'], ondelete='CASCADE')

    op.create_table('userdepartment',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], name='userdepartment_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='userdepartment_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'dept_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_department')
    # ### end Alembic commands ###
