"""new changes

Revision ID: 89bf21194c51
Revises: ee323defd15c
Create Date: 2024-11-18 11:04:52.540080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bf21194c51'
down_revision = 'ee323defd15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('read_permission', sa.Boolean(), nullable=True),
    sa.Column('write_permission', sa.Boolean(), nullable=True),
    sa.Column('delete_permission', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
