"""Fix dept_id foreign key in Permission model

Revision ID: 973fb6fb04f0
Revises: 2dbf5fb81463
Create Date: 2024-11-13 17:19:53.070886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '973fb6fb04f0'
down_revision = '2dbf5fb81463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=False))
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('permissions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['dept_id'], ['dept_id'])
        batch_op.drop_column('folder_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('permissions_ibfk_2', 'folders', ['folder_id'], ['folder_id'])
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
