"""added a new attribute into the folders table

Revision ID: bff6b63a1979
Revises: 456ec5c48773
Create Date: 2024-11-28 14:48:52.177934
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff6b63a1979'
down_revision = '456ec5c48773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_folder_id', sa.Integer(), nullable=True))
        
        # Drop the old foreign key and index
        batch_op.drop_index('fk_department_cascade')
        batch_op.drop_constraint('fk_department_cascade', type_='foreignkey')
        
        # Add new foreign keys
        batch_op.create_foreign_key('fk_department', 'departments', ['dept_id'], ['dept_id'])
        batch_op.create_foreign_key('fk_parent_folder', 'folders', ['parent_folder_id'], ['folder_id'])

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        # Drop the old index
        batch_op.drop_index('fk_folder_cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        # Recreate the old index
        batch_op.create_index('fk_folder_cascade', ['folder_id'], unique=False)

    with op.batch_alter_table('folders', schema=None) as batch_op:
        # Drop the foreign key constraints by name
        batch_op.drop_constraint('fk_parent_folder', type_='foreignkey')
        batch_op.drop_constraint('fk_department', type_='foreignkey')
        
        # Recreate the old index and foreign key
        batch_op.create_index('fk_department_cascade', ['dept_id'], unique=False)
        batch_op.drop_column('parent_folder_id')

    # ### end Alembic commands ###
